services:
  - type: web
    name: image-compressor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MAX_FILE_SIZE
        value: 52428800  # 50MB in bytes
